### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by brando90** [mttk/STL10#1]
I tried running the demo but I found the following error:

```
(venv2) brandomiranda~/Documents/MIT/MEng/hbf_tensorflow_code/tf_tutorials/stl10 $ frameworkpython stl10_input.py
<module 'urllib' from '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/__init__.py'>
Traceback (most recent call last):
  File "stl10_input.py", line 114, in <module>
    download_and_extract()
  File "stl10_input.py", line 108, in download_and_extract
    filepath, _ = urllib.urlretrieve(DATA_URL, filepath, reporthook=_progress)
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

did you ever find an error like this before?

**Comment by brando90** [comment]
seems that:

```
import urllib.request as urllib
```

fixes the issue (for python 3)

**Comment by mttk** [comment]
True, I've written the code in python 2.7 and didn't think about py3; I'll add a quick & dirty fix for compatibility. Thanks.

**Comment by mttk** [comment]
@brando90 should work now, at least the downloading part. I'm assuming the rest stayed the same in py3.
